export const mockRecipes = [
  {
    id: "1",
    title: "Berry Quinoa Breakfast Bowl",
    image:
      "https://images.unsplash.com/photo-1592503469196-3a7880cc2d05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwYnJlYWtmYXN0JTIwYm93bHxlbnwxfHx8fDE3NTg0MzcyMzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    category: "Breakfast",
    ingredients: [
      { id: "1", name: "Quinoa", amount: 1, unit: "cup" },
      { id: "2", name: "Mixed berries", amount: 1, unit: "cup" },
      { id: "3", name: "Almond milk", amount: 0.5, unit: "cup" },
      { id: "4", name: "Honey", amount: 2, unit: "tbsp" },
      { id: "5", name: "Chia seeds", amount: 1, unit: "tbsp" },
      { id: "6", name: "Almonds", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Cook quinoa according to package instructions and let cool",
      "Mix quinoa with almond milk and honey",
      "Top with mixed berries, chia seeds, and almonds",
      "Serve immediately or chill for later",
    ],
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 45,
      fat: 8,
      fiber: 6,
      sugar: 18,
    },
    tags: ["healthy", "breakfast", "quinoa", "berries"],
  },
  {
    id: "2",
    title: "Grilled Chicken Caesar Salad",
    image:
      "https://images.unsplash.com/photo-1604909052743-94e838986d24?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwY2hpY2tlbiUyMHNhbGFkfGVufDF8fHx8MTc1ODQ0NjcyNnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    category: "Lunch",
    ingredients: [
      { id: "7", name: "Chicken breast", amount: 1, unit: "lb" },
      { id: "8", name: "Romaine lettuce", amount: 2, unit: "heads" },
      { id: "9", name: "Parmesan cheese", amount: 0.5, unit: "cup" },
      { id: "10", name: "Caesar dressing", amount: 0.25, unit: "cup" },
      { id: "11", name: "Croutons", amount: 1, unit: "cup" },
      { id: "12", name: "Olive oil", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Season chicken breast with salt and pepper",
      "Grill chicken for 6-7 minutes per side until cooked through",
      "Let chicken rest for 5 minutes, then slice",
      "Toss lettuce with Caesar dressing",
      "Top with grilled chicken, parmesan, and croutons",
    ],
    nutrition: {
      calories: 420,
      protein: 35,
      carbs: 15,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
    tags: ["protein", "salad", "lunch", "grilled"],
  },
  {
    id: "3",
    title: "Creamy Garlic Pasta",
    image:
      "https://images.unsplash.com/photo-1593996470434-890a14b11a6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMGRpbm5lciUyMG1lYWx8ZW58MXx8fHwxNzU4NTEzODQ1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    category: "Dinner",
    ingredients: [
      { id: "13", name: "Fettuccine pasta", amount: 1, unit: "lb" },
      { id: "14", name: "Heavy cream", amount: 1, unit: "cup" },
      { id: "15", name: "Garlic cloves", amount: 4, unit: "pieces" },
      { id: "16", name: "Parmesan cheese", amount: 1, unit: "cup" },
      { id: "17", name: "Butter", amount: 3, unit: "tbsp" },
      { id: "18", name: "Black pepper", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Cook pasta according to package directions",
      "Melt butter in a large pan over medium heat",
      "Add minced garlic and cook for 1 minute",
      "Pour in heavy cream and simmer for 3 minutes",
      "Add cooked pasta and toss with parmesan cheese",
      "Season with black pepper and serve hot",
    ],
    nutrition: {
      calories: 580,
      protein: 18,
      carbs: 65,
      fat: 28,
      fiber: 3,
      sugar: 5,
    },
    tags: ["pasta", "dinner", "creamy", "garlic"],
  },
  {
    id: "4",
    title: "Tropical Green Smoothie",
    image:
      "https://images.unsplash.com/photo-1604298331663-de303fbc7059?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMGZydWl0JTIwc21vb3RoaWV8ZW58MXx8fHwxNzU4NDgyNTcwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    category: "Snack",
    ingredients: [
      { id: "19", name: "Spinach", amount: 2, unit: "cups" },
      { id: "20", name: "Mango chunks", amount: 1, unit: "cup" },
      { id: "21", name: "Pineapple chunks", amount: 0.5, unit: "cup" },
      { id: "22", name: "Coconut milk", amount: 1, unit: "cup" },
      { id: "23", name: "Banana", amount: 1, unit: "piece" },
      { id: "24", name: "Chia seeds", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Add all ingredients to a blender",
      "Blend on high speed for 60 seconds until smooth",
      "Pour into glasses and serve immediately",
      "Garnish with extra chia seeds if desired",
    ],
    nutrition: {
      calories: 180,
      protein: 4,
      carbs: 32,
      fat: 6,
      fiber: 5,
      sugar: 24,
    },
    tags: ["smoothie", "healthy", "tropical", "snack"],
  },
  {
    id: "5",
    title: "Salmon Quinoa Power Bowl",
    image:
      "https://images.unsplash.com/photo-1732759959723-27f1ba1d1fa5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjBxdWlub2ElMjBib3dsfGVufDF8fHx8MTc1ODQ2MzgxNXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 35,
    servings: 2,
    difficulty: "Medium",
    category: "Dinner",
    ingredients: [
      { id: "25", name: "Salmon fillet", amount: 0.75, unit: "lb" },
      { id: "26", name: "Quinoa", amount: 1, unit: "cup" },
      { id: "27", name: "Avocado", amount: 1, unit: "piece" },
      { id: "28", name: "Cucumber", amount: 1, unit: "piece" },
      { id: "29", name: "Cherry tomatoes", amount: 1, unit: "cup" },
      { id: "30", name: "Lemon", amount: 1, unit: "piece" },
    ],
    instructions: [
      "Cook quinoa according to package instructions",
      "Season salmon with salt, pepper, and lemon juice",
      "Pan-sear salmon for 4-5 minutes per side",
      "Slice avocado and cucumber",
      "Assemble bowls with quinoa, salmon, and vegetables",
      "Drizzle with lemon juice and serve",
    ],
    nutrition: {
      calories: 520,
      protein: 35,
      carbs: 42,
      fat: 22,
      fiber: 8,
      sugar: 6,
    },
    tags: ["salmon", "quinoa", "healthy", "bowl"],
  },
  {
    id: "6",
    title: "Chocolate Avocado Mousse",
    image:
      "https://images.unsplash.com/photo-1719228748811-272c2df983af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBhdm9jYWRvJTIwZGVzc2VydHxlbnwxfHx8fDE3NTg1MTM4NTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    category: "Dessert",
    ingredients: [
      { id: "31", name: "Ripe avocados", amount: 2, unit: "pieces" },
      { id: "32", name: "Cocoa powder", amount: 0.25, unit: "cup" },
      { id: "33", name: "Maple syrup", amount: 0.25, unit: "cup" },
      { id: "34", name: "Vanilla extract", amount: 1, unit: "tsp" },
      { id: "35", name: "Almond milk", amount: 3, unit: "tbsp" },
      { id: "36", name: "Sea salt", amount: 0.125, unit: "tsp" },
    ],
    instructions: [
      "Scoop avocado flesh into a food processor",
      "Add cocoa powder, maple syrup, vanilla, and salt",
      "Process until smooth and creamy",
      "Add almond milk gradually until desired consistency",
      "Chill for at least 30 minutes before serving",
      "Garnish with berries or whipped cream if desired",
    ],
    nutrition: {
      calories: 150,
      protein: 3,
      carbs: 18,
      fat: 9,
      fiber: 6,
      sugar: 12,
    },
    tags: ["dessert", "healthy", "chocolate", "avocado"],
  },
];
