/**
 * Mock Recipe Data
 * 
 * This file contains sample recipe data matching the Spoonacular API format.
 * Used during development to preserve API call limits.
 * 
 * Structure matches Spoonacular's recipe search response format.
 * When USE_MOCK_DATA is set to false in recipeService.js,
 * the application will fetch from real APIs instead.
 */

export const mockRecipes = [
  {
    recipes: [
      {
        id: 632250,
        image: "https://img.spoonacular.com/recipes/632250-556x370.jpg",
        imageType: "jpg",
        title: "Alouette Sundried Tomato and Basil Bisque",
        readyInMinutes: 45,
        servings: 8,
        sourceUrl:
          "https://www.foodista.com/recipe/PQVZCRLT/alouette-sundried-tomato-and-basil-bisque",
        vegetarian: false,
        vegan: false,
        glutenFree: true,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 3,
        gaps: "no",
        preparationMinutes: null,
        cookingMinutes: null,
        aggregateLikes: 83,
        healthScore: 0.0,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 45.19,
        extendedIngredients: [
          {
            id: 10123,
            aisle: "Meat",
            image: "raw-bacon.png",
            consistency: "SOLID",
            name: "bacon",
            nameClean: "bacon",
            original: "1 inch oz. Bacon cut in ¼ strips",
            originalName: "oz. Bacon cut in ¼ strips",
            amount: 1.0,
            unit: "inch",
            meta: ["cut in ¼ strips"],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "inch",
                unitLong: "inch",
              },
              metric: {
                amount: 1.0,
                unitShort: "inch",
                unitLong: "inch",
              },
            },
          },
          {
            id: 6159,
            aisle: "Canned and Jarred",
            image: "tomato-soup.png",
            consistency: "LIQUID",
            name: "all natural tomato soup",
            nameClean: "all natural tomato soup",
            original: "1 can Your favorite All Natural Tomato soup",
            originalName: "Your favorite All Natural Tomato soup",
            amount: 1.0,
            unit: "can",
            meta: ["your favorite"],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "can",
                unitLong: "can",
              },
              metric: {
                amount: 1.0,
                unitShort: "can",
                unitLong: "can",
              },
            },
          },
          {
            id: 6615,
            aisle: "Canned and Jarred",
            image: "chicken-broth.png",
            consistency: "LIQUID",
            name: "vegetable stock",
            nameClean: "vegetable stock",
            original: "1 cup Vegetable Stock",
            originalName: "Vegetable Stock",
            amount: 1.0,
            unit: "cup",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "cup",
                unitLong: "cup",
              },
              metric: {
                amount: 235.0,
                unitShort: "ml",
                unitLong: "milliliters",
              },
            },
          },
          {
            id: 99019,
            aisle: "Bakery/Bread",
            image: "tomato-tortillas.jpg",
            consistency: "SOLID",
            name: "alouette all natural sundried tomato and basil spreadable cheese",
            nameClean:
              "alouette all natural sundried tomato and basil spreadable cheese",
            original:
              "1 6.5 oz pkg. Alouette All Natural Sundried Tomato and Basil soft spreadable cheese",
            originalName:
              "pkg. Alouette All Natural Sundried Tomato and Basil soft spreadable cheese",
            amount: 6.5,
            unit: "oz",
            meta: ["soft"],
            measures: {
              us: {
                amount: 6.5,
                unitShort: "oz",
                unitLong: "ounces",
              },
              metric: {
                amount: 184.272,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
        ],
        summary:
          "If you want to add more <b>gluten free and dairy free</b> recipes to your recipe box, Alouette Sundried Tomato and Basil Bisque might be a recipe you should try. One portion of this dish contains about <b>2g of protein</b>, <b>2g of fat</b>, and a total of <b>96 calories</b>. This recipe serves 8 and costs 45 cents per serving. From preparation to the plate, this recipe takes about <b>45 minutes</b>. 83 people were impressed by this recipe. A few people really liked this hor d'oeuvre. If you have bacon, all natural tomato soup, alouette all natural sundried tomato and basil spreadable cheese, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 27%</b>. This score is not so tremendous. Try <a href=\"https://spoonacular.com/recipes/sundried-tomato-basil-and-goats-cheese-pasta-27264\">Sundried Tomato, Basil And Goats Cheese Pasta</a>, <a href=\"https://spoonacular.com/recipes/sundried-tomato-and-basil-cream-cheese-spread-594907\">Sundried Tomato and Basil Cream Cheese Spread</a>, and <a href=\"https://spoonacular.com/recipes/tomato-basil-bisque-211806\">Tomato-Basil Bisque</a> for similar recipes.",
        cuisines: [],
        dishTypes: [
          "antipasti",
          "soup",
          "starter",
          "snack",
          "appetizer",
          "antipasto",
          "hor d'oeuvre",
        ],
        diets: ["gluten free", "dairy free"],
        occasions: [],
        instructions:
          "Saut bacon in heavy gauge sauce pot until crispy\nDrain fat from sauce pot\nAdd Tomato soup and vegetable stock and bring to a boil\nAdd Alouette Sundried Tomato and Basil soft cheese\nBring back to a boil and serve",
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Saut bacon in heavy gauge sauce pot until crispy",
                ingredients: [
                  {
                    id: 10123,
                    name: "bacon",
                    localizedName: "bacon",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png",
                  },
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
                  },
                ],
              },
              {
                number: 2,
                step: "Drain fat from sauce pot",
                ingredients: [
                  {
                    id: 0,
                    name: "sauce",
                    localizedName: "sauce",
                    image: "",
                  },
                ],
                equipment: [
                  {
                    id: 404752,
                    name: "pot",
                    localizedName: "pot",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
                  },
                ],
              },
              {
                number: 3,
                step: "Add Tomato soup and vegetable stock and bring to a boil",
                ingredients: [
                  {
                    id: 6615,
                    name: "vegetable stock",
                    localizedName: "vegetable stock",
                    image: "chicken-broth.png",
                  },
                  {
                    id: 6159,
                    name: "tomato soup",
                    localizedName: "tomato soup",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/tomato-soup.png",
                  },
                ],
                equipment: [],
              },
              {
                number: 4,
                step: "Add Alouette Sundried Tomato and Basil soft cheese",
                ingredients: [
                  {
                    id: 1001017,
                    name: "soft cheese",
                    localizedName: "soft cheese",
                    image: "cream-cheese.jpg",
                  },
                  {
                    id: 11529,
                    name: "tomato",
                    localizedName: "tomato",
                    image: "tomato.png",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Bring back to a boil and serve",
                ingredients: [],
                equipment: [],
              },
            ],
          },
        ],
        originalId: null,
        spoonacularScore: 4.63162899017334,
        spoonacularSourceUrl:
          "https://spoonacular.com/alouette-sundried-tomato-and-basil-bisque-632250",
      },
      {
        id: 664932,
        image: "https://img.spoonacular.com/recipes/664932-556x370.jpg",
        imageType: "jpg",
        title: "Walnut Pesto",
        readyInMinutes: 45,
        servings: 12,
        sourceUrl: "https://www.foodista.com/recipe/3STVPWDF/walnut-pesto",
        vegetarian: false,
        vegan: false,
        glutenFree: true,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 1,
        gaps: "no",
        preparationMinutes: null,
        cookingMinutes: null,
        aggregateLikes: 3,
        healthScore: 5.0,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 46.89,
        extendedIngredients: [
          {
            id: 2044,
            aisle: "Produce",
            image: "fresh-basil.jpg",
            consistency: "SOLID",
            name: "basil leaves",
            nameClean: "basil leaves",
            original: "2 cups fresh basil leaves",
            originalName: "fresh basil leaves",
            amount: 2.0,
            unit: "cups",
            meta: ["fresh"],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "cups",
                unitLong: "cups",
              },
              metric: {
                amount: 48.0,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
          {
            id: 11215,
            aisle: "Produce",
            image: "garlic.png",
            consistency: "SOLID",
            name: "garlic",
            nameClean: "garlic",
            original: "2 cloves garlic",
            originalName: "garlic",
            amount: 2.0,
            unit: "cloves",
            meta: [],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "cloves",
                unitLong: "cloves",
              },
              metric: {
                amount: 2.0,
                unitShort: "cloves",
                unitLong: "cloves",
              },
            },
          },
          {
            id: 4053,
            aisle: "Oil, Vinegar, Salad Dressing",
            image: "olive-oil.jpg",
            consistency: "LIQUID",
            name: "olive oil",
            nameClean: "olive oil",
            original: "cup olive oil",
            originalName: "olive oil",
            amount: 1.0,
            unit: "cup",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "cup",
                unitLong: "cup",
              },
              metric: {
                amount: 216.0,
                unitShort: "ml",
                unitLong: "milliliters",
              },
            },
          },
          {
            id: 1032,
            aisle: "Cheese",
            image: "parmesan.jpg",
            consistency: "SOLID",
            name: "parmesan cheese",
            nameClean: "parmesan cheese",
            original: "3 tablespoons freshly grated Parmesan cheese",
            originalName: "freshly grated Parmesan cheese",
            amount: 3.0,
            unit: "tablespoons",
            meta: ["freshly grated"],
            measures: {
              us: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
              metric: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
            },
          },
          {
            id: 1012047,
            aisle: "Spices and Seasonings",
            image: "salt.jpg",
            consistency: "SOLID",
            name: "sea salt",
            nameClean: "sea salt",
            original: "1 pinch sea salt",
            originalName: "sea salt",
            amount: 1.0,
            unit: "pinch",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "pinch",
                unitLong: "pinch",
              },
              metric: {
                amount: 1.0,
                unitShort: "pinch",
                unitLong: "pinch",
              },
            },
          },
          {
            id: 12155,
            aisle: "Baking",
            image: "walnuts.jpg",
            consistency: "SOLID",
            name: "walnuts",
            nameClean: "walnuts",
            original: "3 tablespoons walnuts",
            originalName: "walnuts",
            amount: 3.0,
            unit: "tablespoons",
            meta: [],
            measures: {
              us: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
              metric: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
            },
          },
        ],
        summary:
          "Walnut Pesto could be just the <b>gluten free and primal</b> recipe you've been looking for. This condiment has <b>55 calories</b>, <b>1g of protein</b>, and <b>6g of fat</b> per serving. For <b>47 cents per serving</b>, this recipe <b>covers 2%</b> of your daily requirements of vitamins and minerals. This recipe serves 12. 3 people have made this recipe and would make it again. Head to the store and pick up basil leaves, garlic, walnuts, and a few other things to make it today. It is brought to you by Foodista. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 43%</b>, which is pretty good. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/walnut-pesto-473307\">Walnut Pesto</a>, <a href=\"https://spoonacular.com/recipes/walnut-pesto-38857\">Walnut Pesto</a>, and <a href=\"https://spoonacular.com/recipes/walnut-pesto-258985\">Walnut Pesto</a>.",
        cuisines: [],
        dishTypes: ["condiment", "dip", "sauce", "spread"],
        diets: ["gluten free", "primal"],
        occasions: [],
        instructions:
          "<ol><li>Combine walnuts, basil, garlic, Parmesan and salt in food processor and process to a coarse puree.</li><li>With the machine running, slowly add the oil. Scrape down the sides and process again. Store pesto in an airtight jar, preferably opaque to keep out the light. Keep pesto covered with a layer of oil to prevent the surface from browning. Store in refrigerator.</li></ol>",
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Combine walnuts, basil, garlic, Parmesan and salt in food processor and process to a coarse puree.With the machine running, slowly add the oil. Scrape down the sides and process again. Store pesto in an airtight jar, preferably opaque to keep out the light. Keep pesto covered with a layer of oil to prevent the surface from browning. Store in refrigerator.",
                ingredients: [
                  {
                    id: 1033,
                    name: "parmesan",
                    localizedName: "parmesan",
                    image: "parmesan.jpg",
                  },
                  {
                    id: 12155,
                    name: "walnuts",
                    localizedName: "walnuts",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/walnuts.jpg",
                  },
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 2044,
                    name: "basil",
                    localizedName: "basil",
                    image: "basil.jpg",
                  },
                  {
                    id: 93698,
                    name: "pesto",
                    localizedName: "pesto",
                    image: "basil-pesto.png",
                  },
                  {
                    id: 2047,
                    name: "salt",
                    localizedName: "salt",
                    image: "salt.jpg",
                  },
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404771,
                    name: "food processor",
                    localizedName: "food processor",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/food-processor.png",
                  },
                ],
              },
            ],
          },
        ],
        originalId: null,
        spoonacularScore: 45.90702819824219,
        spoonacularSourceUrl: "https://spoonacular.com/walnut-pesto-664932",
      },
      {
        id: 716311,
        image: "https://img.spoonacular.com/recipes/716311-556x370.jpg",
        imageType: "jpg",
        title: "Mango Fried Rice",
        readyInMinutes: 45,
        servings: 2,
        sourceUrl: "https://www.afrolems.com/2015/05/02/mango-fried-rice/",
        vegetarian: false,
        vegan: false,
        glutenFree: true,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 12,
        gaps: "no",
        preparationMinutes: null,
        cookingMinutes: null,
        aggregateLikes: 262,
        healthScore: 45.0,
        creditsText: "afrolems.com",
        license: null,
        sourceName: "afrolems.com",
        pricePerServing: 151.08,
        extendedIngredients: [
          {
            id: 6172,
            aisle: "Canned and Jarred",
            image: "chicken-broth.png",
            consistency: "LIQUID",
            name: "chicken stock",
            nameClean: "chicken stock",
            original: "2 cups of chicken stock",
            originalName: "chicken stock",
            amount: 2.0,
            unit: "cups",
            meta: [],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "cups",
                unitLong: "cups",
              },
              metric: {
                amount: 480.0,
                unitShort: "ml",
                unitLong: "milliliters",
              },
            },
          },
          {
            id: 99186,
            aisle: "Meat",
            image: "diced-ham.jpg",
            consistency: "SOLID",
            name: "seasoning cubes",
            nameClean: "seasoning cubes",
            original: "Seasoning cubes",
            originalName: "Seasoning cubes",
            amount: 2.0,
            unit: "servings",
            meta: [],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "servings",
                unitLong: "servings",
              },
              metric: {
                amount: 2.0,
                unitShort: "servings",
                unitLong: "servings",
              },
            },
          },
          {
            id: 9176,
            aisle: "Produce",
            image: "mango.jpg",
            consistency: "SOLID",
            name: "mango",
            nameClean: "mango",
            original: "3 slices of mango cubed",
            originalName: "mango cubed",
            amount: 3.0,
            unit: "slices",
            meta: ["cubed"],
            measures: {
              us: {
                amount: 3.0,
                unitShort: "slice",
                unitLong: "slices",
              },
              metric: {
                amount: 3.0,
                unitShort: "slice",
                unitLong: "slices",
              },
            },
          },
          {
            id: 20444,
            aisle: "Pasta and Rice",
            image: "uncooked-white-rice.png",
            consistency: "SOLID",
            name: "rice",
            nameClean: "rice",
            original: "1 cup of rice",
            originalName: "rice",
            amount: 1.0,
            unit: "cup",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "cup",
                unitLong: "cup",
              },
              metric: {
                amount: 185.0,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
          {
            id: 11583,
            aisle: "Frozen",
            image: "mixed-vegetables.png",
            consistency: "SOLID",
            name: "vegetables",
            nameClean: "vegetables",
            original: "1 cup of chopped vegetables",
            originalName: "chopped vegetables",
            amount: 1.0,
            unit: "cup",
            meta: ["chopped"],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "cup",
                unitLong: "cup",
              },
              metric: {
                amount: 182.0,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
          {
            id: 10011819,
            aisle: "Ethnic Foods",
            image: "habanero-pepper.jpg",
            consistency: "SOLID",
            name: "scotch bonnet pepper",
            nameClean: "scotch bonnet pepper",
            original: "1 scotch bonnet pepper",
            originalName: "scotch bonnet pepper",
            amount: 1.0,
            unit: "",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "",
                unitLong: "",
              },
              metric: {
                amount: 1.0,
                unitShort: "",
                unitLong: "",
              },
            },
          },
        ],
        summary:
          "Mango Fried Rice is a Chinese main course. This recipe makes 2 servings with <b>486 calories</b>, <b>16g of protein</b>, and <b>4g of fat</b> each. For <b>$1.51 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. Several people made this recipe, and 262 would say it hit the spot. Head to the store and pick up scotch bonnet pepper, seasoning cubes, rice, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is brought to you by Afrolems. It is a good option if you're following a <b>gluten free and dairy free</b> diet. Overall, this recipe earns a <b>great spoonacular score of 94%</b>. <a href=\"https://spoonacular.com/recipes/mango-pork-fried-rice-176007\">Mango-Pork Fried Rice</a>, <a href=\"https://spoonacular.com/recipes/thai-beef-mango-fried-rice-1326163\">Thai Beef & Mango Fried Rice</a>, and <a href=\"https://spoonacular.com/recipes/thai-chicken-and-mango-fried-rice-509300\">Thai Chicken and Mango Fried Rice</a> are very similar to this recipe.",
        cuisines: ["Chinese", "Asian"],
        dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
        diets: ["gluten free", "dairy free"],
        occasions: [],
        instructions:
          "Wash your rice and bring to boil on medium heat with very little water as you are still going to cook it in chicken stock.Once the rice is slightly soft and the initial water has dried up, reduce the heat and pour in the chicken stock and cook till the chicken stock is all absorbed and has dried up. The chicken stock if freshly made will have some oil from the chicken so your rice does not need oil.Increase the heat and stir in the chopped vegetables and pepper. Add your seasoning cube.Finally stir in your cubed mango and serve warm with any protein of your choice. I’d say chicken but it’s up to you.",
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Wash your rice and bring to boil on medium heat with very little water as you are still going to cook it in chicken stock.Once the rice is slightly soft and the initial water has dried up, reduce the heat and pour in the chicken stock and cook till the chicken stock is all absorbed and has dried up. The chicken stock if freshly made will have some oil from the chicken so your rice does not need oil.Increase the heat and stir in the chopped vegetables and pepper.",
                ingredients: [
                  {
                    id: 6172,
                    name: "chicken stock",
                    localizedName: "chicken stock",
                    image: "chicken-broth.png",
                  },
                  {
                    id: 11583,
                    name: "vegetable",
                    localizedName: "vegetable",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/mixed-vegetables.png",
                  },
                  {
                    id: 0,
                    name: "chicken",
                    localizedName: "chicken",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg",
                  },
                  {
                    id: 1002030,
                    name: "pepper",
                    localizedName: "pepper",
                    image: "pepper.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 20444,
                    name: "rice",
                    localizedName: "rice",
                    image: "uncooked-white-rice.png",
                  },
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 2,
                step: "Add your seasoning cube.Finally stir in your cubed mango and serve warm with any protein of your choice. I’d say chicken but it’s up to you.",
                ingredients: [
                  {
                    id: 0,
                    name: "seasoning cube",
                    localizedName: "seasoning cube",
                    image: "stock-cube.jpg",
                  },
                  {
                    id: 0,
                    name: "chicken",
                    localizedName: "chicken",
                    image:
                      "https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg",
                  },
                  {
                    id: 9176,
                    name: "mango",
                    localizedName: "mango",
                    image: "mango.jpg",
                  },
                ],
                equipment: [],
              },
            ],
          },
        ],
        originalId: null,
        spoonacularScore: 96.9690170288086,
        spoonacularSourceUrl: "https://spoonacular.com/mango-fried-rice-716311",
      },
      {
        id: 642169,
        image: "https://img.spoonacular.com/recipes/642169-556x370.jpg",
        imageType: "jpg",
        title: "Edamame Hummus",
        readyInMinutes: 45,
        servings: 6,
        sourceUrl: "https://www.foodista.com/recipe/JP74GT52/edamame-hummus",
        vegetarian: true,
        vegan: true,
        glutenFree: true,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 5,
        gaps: "no",
        preparationMinutes: null,
        cookingMinutes: null,
        aggregateLikes: 4,
        healthScore: 8.0,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 67.41,
        extendedIngredients: [
          {
            id: 1032009,
            aisle: "Spices and Seasonings",
            image: "red-pepper-flakes.jpg",
            consistency: "SOLID",
            name: "chili flakes",
            nameClean: "chili flakes",
            original: "¼ teaspoon chili flakes (if you like it spicy)",
            originalName: "chili flakes (if you like it spicy)",
            amount: 0.25,
            unit: "teaspoon",
            meta: ["(if you like it spicy)"],
            measures: {
              us: {
                amount: 0.25,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
              metric: {
                amount: 0.25,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
            },
          },
          {
            id: 99296,
            aisle: "Health Foods",
            image: "edamame.png",
            consistency: "SOLID",
            name: "edamame",
            nameClean: "edamame",
            original: "8 oz. Edamame",
            originalName: "Edamame",
            amount: 8.0,
            unit: "oz",
            meta: [],
            measures: {
              us: {
                amount: 8.0,
                unitShort: "oz",
                unitLong: "ounces",
              },
              metric: {
                amount: 226.796,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
          {
            id: 10211297,
            aisle: "Produce",
            image: "parsley.jpg",
            consistency: "SOLID",
            name: "flat-leaf parsley",
            nameClean: "flat-leaf parsley",
            original: "1 tablespoon chopped, fresh flat-leaf parsley",
            originalName: "chopped, fresh flat-leaf parsley",
            amount: 1.0,
            unit: "tablespoon",
            meta: ["fresh", "chopped"],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "Tbsp",
                unitLong: "Tbsp",
              },
              metric: {
                amount: 1.0,
                unitShort: "Tbsp",
                unitLong: "Tbsp",
              },
            },
          },
          {
            id: 11215,
            aisle: "Produce",
            image: "garlic.png",
            consistency: "SOLID",
            name: "garlic",
            nameClean: "garlic",
            original: "4 cloves garlic minced",
            originalName: "garlic minced",
            amount: 4.0,
            unit: "cloves",
            meta: ["minced"],
            measures: {
              us: {
                amount: 4.0,
                unitShort: "cloves",
                unitLong: "cloves",
              },
              metric: {
                amount: 4.0,
                unitShort: "cloves",
                unitLong: "cloves",
              },
            },
          },
          {
            id: 1002013,
            aisle: "Spices and Seasonings",
            image: "ground-coriander.jpg",
            consistency: "SOLID",
            name: "ground coriander",
            nameClean: "ground coriander",
            original: "¼ teaspoon ground coriander",
            originalName: "ground coriander",
            amount: 0.25,
            unit: "teaspoon",
            meta: [],
            measures: {
              us: {
                amount: 0.25,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
              metric: {
                amount: 0.25,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
            },
          },
          {
            id: 1012014,
            aisle: "Spices and Seasonings",
            image: "ground-cumin.jpg",
            consistency: "SOLID",
            name: "ground cumin",
            nameClean: "ground cumin",
            original: "½ teaspoon ground cumin",
            originalName: "ground cumin",
            amount: 0.5,
            unit: "teaspoon",
            meta: [],
            measures: {
              us: {
                amount: 0.5,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
              metric: {
                amount: 0.5,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
            },
          },
          {
            id: 1082047,
            aisle: "Spices and Seasonings",
            image: "salt.jpg",
            consistency: "SOLID",
            name: "kosher salt",
            nameClean: "kosher salt",
            original: "¾ teaspoon Kosher salt",
            originalName: "Kosher salt",
            amount: 0.75,
            unit: "teaspoon",
            meta: [],
            measures: {
              us: {
                amount: 0.75,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
              metric: {
                amount: 0.75,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
            },
          },
          {
            id: 9150,
            aisle: "Produce",
            image: "lemon.png",
            consistency: "SOLID",
            name: "lemon",
            nameClean: "lemon",
            original: "1 lemon",
            originalName: "lemon",
            amount: 1.0,
            unit: "",
            meta: [],
            measures: {
              us: {
                amount: 1.0,
                unitShort: "",
                unitLong: "",
              },
              metric: {
                amount: 1.0,
                unitShort: "",
                unitLong: "",
              },
            },
          },
          {
            id: 9156,
            aisle: "Produce",
            image: "zest-lemon.jpg",
            consistency: "SOLID",
            name: "lemon zest",
            nameClean: "lemon zest",
            original: "½ teaspoon freshly grated lemon zest",
            originalName: "freshly grated lemon zest",
            amount: 0.5,
            unit: "teaspoon",
            meta: ["freshly grated"],
            measures: {
              us: {
                amount: 0.5,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
              metric: {
                amount: 0.5,
                unitShort: "tsps",
                unitLong: "teaspoons",
              },
            },
          },
          {
            id: 1034053,
            aisle: "Oil, Vinegar, Salad Dressing",
            image: "olive-oil.jpg",
            consistency: "LIQUID",
            name: "olive oil",
            nameClean: "olive oil",
            original: "3 tablespoons extra-virgin olive oil",
            originalName: "extra-virgin olive oil",
            amount: 3.0,
            unit: "tablespoons",
            meta: ["extra-virgin"],
            measures: {
              us: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
              metric: {
                amount: 3.0,
                unitShort: "Tbsps",
                unitLong: "Tbsps",
              },
            },
          },
          {
            id: 12698,
            aisle: "Health Foods",
            image: "tahini-paste.png",
            consistency: "SOLID",
            name: "tahini",
            nameClean: "tahini",
            original: "¼ cup Tahini (sesame-seed paste)",
            originalName: "Tahini (sesame-seed paste)",
            amount: 0.25,
            unit: "cup",
            meta: ["(sesame-seed paste)"],
            measures: {
              us: {
                amount: 0.25,
                unitShort: "cups",
                unitLong: "cups",
              },
              metric: {
                amount: 60.0,
                unitShort: "ml",
                unitLong: "milliliters",
              },
            },
          },
          {
            id: 14412,
            aisle: "Beverages",
            image: "water.png",
            consistency: "LIQUID",
            name: "water",
            nameClean: "water",
            original: "3 cups of Water",
            originalName: "Water",
            amount: 3.0,
            unit: "cups",
            meta: [],
            measures: {
              us: {
                amount: 3.0,
                unitShort: "cups",
                unitLong: "cups",
              },
              metric: {
                amount: 709.764,
                unitShort: "ml",
                unitLong: "milliliters",
              },
            },
          },
        ],
        summary:
          "Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan hor d'oeuvre</b>? Edamame Hummus could be an awesome recipe to try. This recipe serves 6. For <b>67 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. One serving contains <b>177 calories</b>, <b>6g of protein</b>, and <b>14g of fat</b>. It is brought to you by Foodista. 4 people were glad they tried this recipe. This recipe is typical of middl eastern cuisine. If you have ground coriander, garlic, flat-leaf parsley, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 56%</b>. <a href=\"https://spoonacular.com/recipes/edamame-hummus-330423\">Edamame Hummus</a>, <a href=\"https://spoonacular.com/recipes/edamame-hummus-527611\">Edamame Hummus</a>, and <a href=\"https://spoonacular.com/recipes/edamame-hummus-567530\">Edamame Hummus</a> are very similar to this recipe.",
        cuisines: ["Middle Eastern"],
        dishTypes: [
          "antipasti",
          "condiment",
          "starter",
          "snack",
          "appetizer",
          "dip",
          "antipasto",
          "hor d'oeuvre",
          "spread",
        ],
        diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
        occasions: [],
        instructions:
          "<ol><li>Boil the edamame in salted water for 4 to 5 minutes.  Drain.</li><li>In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.</li><li>With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.</li><li>Transfer to a small bowl, stir in the parsley and drizzle with remaining oil. Serve, or refrigerate, covered, up to 3 days.</li></ol>",
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Boil the edamame in salted water for 4 to 5 minutes.",
                ingredients: [
                  {
                    id: 99296,
                    name: "edamame",
                    localizedName: "edamame",
                    image: "edamame.png",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [],
                length: {
                  number: 4,
                  unit: "minutes",
                },
              },
              {
                number: 2,
                step: "Drain.In a food processor, puree the Edamame, tahini, water, lemon zest and juice, garlic, salt, cumin, coriander, and chili flakes (optional) until smooth.With the motor running, slowly drizzle in 2 tablespoons of olive oil and mix until absorbed.",
                ingredients: [
                  {
                    id: 1032009,
                    name: "red pepper flakes",
                    localizedName: "red pepper flakes",
                    image: "red-pepper-flakes.jpg",
                  },
                  {
                    id: 9156,
                    name: "lemon zest",
                    localizedName: "lemon zest",
                    image: "zest-lemon.jpg",
                  },
                  {
                    id: 1012013,
                    name: "coriander",
                    localizedName: "coriander",
                    image: "ground-coriander.jpg",
                  },
                  {
                    id: 4053,
                    name: "olive oil",
                    localizedName: "olive oil",
                    image: "olive-oil.jpg",
                  },
                  {
                    id: 99296,
                    name: "edamame",
                    localizedName: "edamame",
                    image: "edamame.png",
                  },
                  {
                    id: 11215,
                    name: "garlic",
                    localizedName: "garlic",
                    image: "garlic.png",
                  },
                  {
                    id: 12698,
                    name: "tahini",
                    localizedName: "tahini",
                    image: "tahini-paste.png",
                  },
                  {
                    id: 1002014,
                    name: "cumin",
                    localizedName: "cumin",
                    image: "ground-cumin.jpg",
                  },
                  {
                    id: 1019016,
                    name: "juice",
                    localizedName: "juice",
                    image: "apple-juice.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                  {
                    id: 2047,
                    name: "salt",
                    localizedName: "salt",
                    image: "salt.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404771,
                    name: "food processor",
                    localizedName: "food processor",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/food-processor.png",
                  },
                ],
              },
              {
                number: 3,
                step: "Transfer to a small bowl, stir in the parsley and drizzle with remaining oil.",
                ingredients: [
                  {
                    id: 11297,
                    name: "parsley",
                    localizedName: "parsley",
                    image: "parsley.jpg",
                  },
                  {
                    id: 4582,
                    name: "cooking oil",
                    localizedName: "cooking oil",
                    image: "vegetable-oil.jpg",
                  },
                ],
                equipment: [
                  {
                    id: 404783,
                    name: "bowl",
                    localizedName: "bowl",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                  },
                ],
              },
              {
                number: 4,
                step: "Serve, or refrigerate, covered, up to 3 days.",
                ingredients: [],
                equipment: [],
              },
            ],
          },
        ],
        originalId: null,
        spoonacularScore: 53.693729400634766,
        spoonacularSourceUrl: "https://spoonacular.com/edamame-hummus-642169",
      },
      {
        id: 636874,
        image: "https://img.spoonacular.com/recipes/636874-556x370.jpg",
        imageType: "jpg",
        title: "Candy Cane Chocolate Marshmallows",
        readyInMinutes: 75,
        servings: 24,
        sourceUrl:
          "https://www.foodista.com/recipe/SW55NN82/candy-cane-chocolate-marshmallows",
        vegetarian: false,
        vegan: false,
        glutenFree: true,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 2,
        gaps: "no",
        preparationMinutes: null,
        cookingMinutes: null,
        aggregateLikes: 2,
        healthScore: 0.0,
        creditsText:
          "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
        license: "CC BY 3.0",
        sourceName: "Foodista",
        pricePerServing: 17.75,
        extendedIngredients: [
          {
            id: 93759,
            aisle: "Sweet Snacks",
            image: "candy-canes.jpg",
            consistency: "SOLID",
            name: "candy canes",
            nameClean: "candy canes",
            original: "6 organic candy canes, crushed",
            originalName: "organic candy canes, crushed",
            amount: 6.0,
            unit: "",
            meta: ["organic", "crushed"],
            measures: {
              us: {
                amount: 6.0,
                unitShort: "",
                unitLong: "",
              },
              metric: {
                amount: 6.0,
                unitShort: "",
                unitLong: "",
              },
            },
          },
          {
            id: 19904,
            aisle: "Sweet Snacks",
            image: "dark-chocolate-pieces.jpg",
            consistency: "SOLID",
            name: "chocolate",
            nameClean: "chocolate",
            original: "2 ounces dark chocolate",
            originalName: "dark chocolate",
            amount: 2.0,
            unit: "ounces",
            meta: ["dark"],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "oz",
                unitLong: "ounces",
              },
              metric: {
                amount: 56.699,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
          {
            id: 19116,
            aisle: "Baking",
            image: "normal-marshmallows.jpg",
            consistency: "SOLID",
            name: "marshmallows",
            nameClean: "marshmallows",
            original: "24 marshmallows",
            originalName: "marshmallows",
            amount: 24.0,
            unit: "",
            meta: [],
            measures: {
              us: {
                amount: 24.0,
                unitShort: "",
                unitLong: "",
              },
              metric: {
                amount: 24.0,
                unitShort: "",
                unitLong: "",
              },
            },
          },
          {
            id: 19081,
            aisle: "Sweet Snacks",
            image: "milk-chocolate.jpg",
            consistency: "SOLID",
            name: "milk chocolate",
            nameClean: "milk chocolate",
            original: "2 ounces milk chocolate",
            originalName: "milk chocolate",
            amount: 2.0,
            unit: "ounces",
            meta: [],
            measures: {
              us: {
                amount: 2.0,
                unitShort: "oz",
                unitLong: "ounces",
              },
              metric: {
                amount: 56.699,
                unitShort: "g",
                unitLong: "grams",
              },
            },
          },
        ],
        summary:
          "Candy Cane Chocolate Marshmallows might be a good recipe to expand your hor d'oeuvre recipe box. Watching your figure? This gluten free recipe has <b>48 calories</b>, <b>0g of protein</b>, and <b>2g of fat</b> per serving. This recipe serves 24 and costs 18 cents per serving. A mixture of candy canes, chocolate, milk chocolate, and a handful of other ingredients are all it takes to make this recipe so delicious. 2 people found this recipe to be flavorful and satisfying. It is perfect for <b>Christmas</b>. From preparation to the plate, this recipe takes about <b>1 hour and 15 minutes</b>. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 9%</b>. This score is improvable. Try <a href=\"https://spoonacular.com/recipes/candy-cane-chocolate-marshmallows-1396529\">Candy Cane Chocolate Marshmallows</a>, <a href=\"https://spoonacular.com/recipes/candy-cane-chocolate-marshmallows-1497411\">Candy Cane Chocolate Marshmallows</a>, and <a href=\"https://spoonacular.com/recipes/peppermint-candy-cane-marshmallows-590382\">Peppermint Candy Cane Marshmallows</a> for similar recipes.",
        cuisines: [],
        dishTypes: [
          "antipasti",
          "starter",
          "snack",
          "appetizer",
          "antipasto",
          "hor d'oeuvre",
        ],
        diets: ["gluten free"],
        occasions: ["christmas"],
        instructions:
          "<ol><li>Crush candy canes (use bottom of a glass, mallet, whatever works)</li><li>Over double burner (or other concoction where the chocolate doesnt touch the water), melt chocolate</li><li>Dip marshmallow into chocolate, then into crushed candy cane</li><li>Set on wax paper</li><li>Chill for at least an hour or until chocolate hardens</li><li>Store in airtight container</li><li>Enjoy alone or dunk in a mug of hot chocolate.</li></ol>",
        analyzedInstructions: [
          {
            name: "",
            steps: [
              {
                number: 1,
                step: "Crush candy canes (use bottom of a glass, mallet, whatever works)Over double burner (or other concoction where the chocolate doesnt touch the water), melt chocolate",
                ingredients: [
                  {
                    id: 93759,
                    name: "candy cane",
                    localizedName: "candy cane",
                    image: "candy-canes.jpg",
                  },
                  {
                    id: 19081,
                    name: "chocolate",
                    localizedName: "chocolate",
                    image: "milk-chocolate.jpg",
                  },
                  {
                    id: 14412,
                    name: "water",
                    localizedName: "water",
                    image: "water.png",
                  },
                ],
                equipment: [],
              },
              {
                number: 2,
                step: "Dip marshmallow into chocolate, then into crushed candy cane",
                ingredients: [
                  {
                    id: 19116,
                    name: "marshmallows",
                    localizedName: "marshmallows",
                    image: "normal-marshmallows.jpg",
                  },
                  {
                    id: 93759,
                    name: "candy cane",
                    localizedName: "candy cane",
                    image: "candy-canes.jpg",
                  },
                  {
                    id: 19081,
                    name: "chocolate",
                    localizedName: "chocolate",
                    image: "milk-chocolate.jpg",
                  },
                  {
                    id: 0,
                    name: "dip",
                    localizedName: "dip",
                    image: "",
                  },
                ],
                equipment: [],
              },
              {
                number: 3,
                step: "Set on wax paper",
                ingredients: [],
                equipment: [
                  {
                    id: 404739,
                    name: "wax paper",
                    localizedName: "wax paper",
                    image:
                      "https://spoonacular.com/cdn/equipment_100x100/wax-paper.jpg",
                  },
                ],
              },
              {
                number: 4,
                step: "Chill for at least an hour or until chocolate hardens",
                ingredients: [
                  {
                    id: 19081,
                    name: "chocolate",
                    localizedName: "chocolate",
                    image: "milk-chocolate.jpg",
                  },
                ],
                equipment: [],
              },
              {
                number: 5,
                step: "Store in airtight container",
                ingredients: [],
                equipment: [],
              },
              {
                number: 6,
                step: "Enjoy alone or dunk in a mug of hot chocolate.",
                ingredients: [
                  {
                    id: 14194,
                    name: "hot chocolate",
                    localizedName: "hot chocolate",
                    image: "hot-drink.jpg",
                  },
                ],
                equipment: [],
              },
            ],
          },
        ],
        originalId: null,
        spoonacularScore: 11.649014472961426,
        spoonacularSourceUrl:
          "https://spoonacular.com/candy-cane-chocolate-marshmallows-636874",
      },
    ],
  },
];
